# Generated by Django 3.1.4 on 2021-03-29 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address_id',
            field=models.ForeignKey(db_column='address_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.address'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='photographer_id',
            field=models.ForeignKey(db_column='photographer_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.photographer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.user_details'),
        ),
        migrations.AlterField(
            model_name='area_details',
            name='city_id',
            field=models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.city_details'),
        ),
        migrations.AlterField(
            model_name='city_details',
            name='state_id',
            field=models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.state_details'),
        ),
        migrations.AlterField(
            model_name='contributor_payment_details',
            name='image_id',
            field=models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.image'),
        ),
        migrations.AlterField(
            model_name='contributor_payment_details',
            name='pay_id',
            field=models.ForeignKey(db_column='pay_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.payment'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.user_details'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.user_details'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='image_id',
            field=models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.image'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appoint_id',
            field=models.ForeignKey(db_column='appoint_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_details_id',
            field=models.ForeignKey(db_column='pay_details_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.payment_details'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.user_details'),
        ),
        migrations.AlterField(
            model_name='tag_link',
            name='image_id',
            field=models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.image'),
        ),
        migrations.AlterField(
            model_name='tag_link',
            name='tag_id',
            field=models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.tags'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='address_id',
            field=models.ForeignKey(blank=True, db_column='address_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Appointment.address'),
        ),
    ]
