# Generated by Django 3.1.4 on 2021-03-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_auto_20210329_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
