# Generated by Django 3.1.4 on 2021-03-29 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_auto_20210329_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='userobj',
            field=models.ForeignKey(db_column='userobj', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
