# Generated by Django 3.1.4 on 2021-04-04 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0007_auto_20210331_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.user_details')),
            ],
            options={
                'verbose_name_plural': 'Cart',
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Cart_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.ForeignKey(db_column='cart_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.cart')),
                ('image_id', models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.image')),
            ],
            options={
                'verbose_name_plural': 'Cart Details',
                'db_table': 'Cart_Details',
            },
        ),
    ]
