# Generated by Django 3.1.4 on 2021-04-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0008_cart_cart_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag_Link',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
