# Generated by Django 3.1.4 on 2021-04-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0009_auto_20210407_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
