# Generated by Django 3.1.4 on 2021-04-07 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0012_auto_20210407_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='area',
            field=models.ForeignKey(db_column='area', on_delete=django.db.models.deletion.CASCADE, to='Appointment.area_details'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(db_column='city', on_delete=django.db.models.deletion.CASCADE, to='Appointment.city_details'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.CASCADE, to='Appointment.state_details'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='event',
            field=models.ForeignKey(db_column='event', on_delete=django.db.models.deletion.CASCADE, to='Appointment.event_types'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(db_column='location', on_delete=django.db.models.deletion.CASCADE, to='Appointment.location_details'),
        ),
    ]
