# Generated by Django 3.2 on 2021-04-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0014_like_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelTable(
            name='images',
            table='Images',
        ),
    ]
