# Generated by Django 3.2 on 2021-04-10 23:43

import Appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0015_auto_20210410_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='profile_photo',
            field=models.ImageField(default='stockimages/profile/photos/default-profile-photo.png', upload_to=Appointment.models.User_Details.user_based_upload_to),
        ),
    ]
