# Generated by Django 3.2 on 2021-04-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0016_user_details_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_types',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
