# Generated by Django 3.2 on 2021-04-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0017_alter_event_types_estimated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='photographer_id',
            field=models.ForeignKey(blank=True, db_column='photographer_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.photographer'),
        ),
    ]
