# Generated by Django 3.2 on 2021-04-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0018_alter_appointment_photographer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('DC', 'Debit Card'), ('CC', 'Credit Card'), ('U', 'UPI')], max_length=20),
        ),
    ]
