# Generated by Django 3.2 on 2021-04-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0019_alter_payment_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, default='Due', max_length=10, null=True),
        ),
    ]
