# Generated by Django 3.2 on 2021-04-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0020_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'get_latest_by': ['user_id'], 'verbose_name_plural': 'Appointment'},
        ),
    ]
