# Generated by Django 3.2 on 2021-04-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0021_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='appoint_id',
            field=models.ForeignKey(blank=True, db_column='appoint_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(blank=True, db_column='order_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.order'),
        ),
    ]
