# Generated by Django 3.2 on 2021-04-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0022_auto_20210418_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
