# Generated by Django 3.2 on 2021-04-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0023_alter_payment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
