# Generated by Django 3.2 on 2021-05-11 06:01

import Appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0024_auto_20210418_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_thumb',
            field=models.ImageField(default='', upload_to=Appointment.models.Images.user_based_upload_to_thumb),
        ),
    ]
