# Generated by Django 3.2 on 2021-05-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0025_images_image_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default='P', max_length=15),
        ),
    ]
