# Generated by Django 3.2 on 2021-05-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0026_alter_images_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.categories'),
        ),
        migrations.AlterField(
            model_name='images',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_format',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='resolution',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
