# Generated by Django 3.2 on 2021-05-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0027_auto_20210516_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
