# Generated by Django 3.2 on 2021-05-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0028_auto_20210516_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='fordeveloper',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
