# Generated by Django 3.2.3 on 2021-05-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0029_images_fordeveloper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='photographer_id',
        ),
        migrations.AddField(
            model_name='images',
            name='downloads',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Appointment_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoint_id', models.ForeignKey(blank=True, db_column='appoint_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.appointment')),
                ('photographer_id', models.ForeignKey(blank=True, db_column='photographer_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.photographer')),
            ],
            options={
                'verbose_name_plural': 'Appointment Details',
                'db_table': 'Appointment_Details',
            },
        ),
    ]
