# Generated by Django 3.2.3 on 2021-05-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0030_auto_20210525_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'get_latest_by': ['date'], 'verbose_name_plural': 'Appointment'},
        ),
        migrations.CreateModel(
            name='Event_Location_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(blank=True, db_column='event_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.event_types')),
                ('location_id', models.ForeignKey(blank=True, db_column='location_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.location_details')),
            ],
            options={
                'verbose_name_plural': 'Event Location Details',
                'db_table': 'Event_Location_Details',
            },
        ),
    ]
