# Generated by Django 3.2.3 on 2021-05-28 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0031_auto_20210527_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='photographer_id',
            field=models.ForeignKey(blank=True, db_column='photographer_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.photographer'),
        ),
        migrations.DeleteModel(
            name='Appointment_Details',
        ),
    ]
