# Generated by Django 3.2.3 on 2021-05-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0033_auto_20210528_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='eventdays',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='video_duration',
        ),
    ]
