# Generated by Django 3.2.3 on 2021-05-30 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0034_auto_20210529_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address_id',
            field=models.ForeignKey(blank=True, db_column='address_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.address'),
        ),
    ]
