# Generated by Django 3.2.3 on 2021-05-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0035_alter_appointment_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='remaining_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
