# Generated by Django 3.2.3 on 2021-06-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0036_auto_20210530_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='edited_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
