# Generated by Django 3.2.3 on 2021-06-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0039_alter_appointment_appoint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor_payment_details',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='contributor_payment_details',
            name='pay_id',
        ),
        migrations.AlterField(
            model_name='contributor_payment_details',
            name='image_id',
            field=models.ForeignKey(blank=True, db_column='image_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.images'),
        ),
        migrations.CreateModel(
            name='Contributor_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pay_id', models.ForeignKey(db_column='pay_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.payment')),
            ],
            options={
                'verbose_name_plural': 'Contributor Payment',
                'db_table': 'Contributor_Payment',
            },
        ),
        migrations.AddField(
            model_name='contributor_payment_details',
            name='cont_pay_id',
            field=models.ForeignKey(db_column='cont_pay_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Appointment.contributor_payment'),
        ),
    ]
