# Generated by Django 3.2.3 on 2021-06-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0040_auto_20210603_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor_payment',
            name='payment_datetime',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
