# Generated by Django 3.2.3 on 2021-06-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0041_contributor_payment_payment_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor_payment',
            name='pay_id',
        ),
        migrations.AddField(
            model_name='contributor_payment',
            name='pay_details_id',
            field=models.ForeignKey(db_column='pay_details_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Appointment.payment_details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributor_payment_details',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
