# Generated by Django 3.2.3 on 2021-06-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0042_auto_20210603_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor_payment_details',
            name='downloads_when_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
