# Generated by Django 3.2.3 on 2021-06-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0043_contributor_payment_details_downloads_when_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor_payment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
