# Generated by Django 3.2.3 on 2021-06-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0045_contributor_payment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='total_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
