# Generated by Django 3.2.3 on 2021-06-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0046_images_total_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='remaining_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
