# Generated by Django 3.2.3 on 2021-06-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0047_auto_20210606_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remaining_Contributor_Payment',
            fields=[
                ('rem_cont_pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('addedon', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='Appointment.user_details')),
            ],
            options={
                'verbose_name_plural': 'Remaining Contributor Payment',
                'db_table': 'Remaining_Contributor_Payment',
            },
        ),
        migrations.CreateModel(
            name='Remaining_Contributor_Payment_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloads_when_purchased', models.IntegerField(blank=True, default=0, null=True)),
                ('payment_status', models.BooleanField(blank=True, default=False, null=True)),
                ('image_id', models.ForeignKey(blank=True, db_column='image_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.images')),
                ('rem_cont_pay_id', models.ForeignKey(db_column='rem_cont_pay_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Appointment.remaining_contributor_payment')),
            ],
            options={
                'verbose_name_plural': 'Remaining Contributor Payment Details',
                'db_table': 'Remaining_Contributor_Payment_Details',
            },
        ),
    ]
