# Generated by Django 3.2.3 on 2021-06-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0048_remaining_contributor_payment_remaining_contributor_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=8, null=True),
        ),
    ]
