# Generated by Django 3.2.3 on 2021-06-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0049_alter_images_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='total_earnings',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=8, null=True),
        ),
    ]
