# Generated by Django 3.2.3 on 2021-06-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0051_auto_20210629_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='total_unpaid_earnings',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=8, null=True),
        ),
    ]
